[project]
name = 'Decentralized-Retail-Inventory-Optimization-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.product-registration]
path = 'contracts/product-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.retail-inventory-system]
path = 'contracts/retail-inventory-system.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
